In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("C:/Users/ravi9/Downloads/trends.csv")

In [3]:
df

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26955 rows x 5 columns]

In [4]:
df.head()

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [5]:
df.tail()

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [6]:
df.shape

(26955, 5)

In [7]:
df.describe()

               year         rank
count  26955.000000  26955.00000
mean    2015.243369      3.00000
std        3.564683      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [8]:
df.isnull()

       location   year  category   rank  query
0         False  False     False  False  False
1         False  False     False  False  False
2         False  False     False  False  False
3         False  False     False  False  False
4         False  False     False  False  False
...         ...    ...       ...    ...    ...
26950     False  False     False  False  False
26951     False  False     False  False  False
26952     False  False     False  False  False
26953     False  False     False  False  False
26954     False  False     False  False  False

[26955 rows x 5 columns]

In [9]:
df.nunique()

location       83
year           20
category     2450
rank            5
query       18431
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(10)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
df

      location  year         category  rank                query
0       Global  2001  Consumer Brands     1                Nokia
1       Global  2001  Consumer Brands     2                 Sony
2       Global  2001  Consumer Brands     3                  BMW
3       Global  2001  Consumer Brands     4                 Palm
4       Global  2001  Consumer Brands     5                Adobe
...        ...   ...              ...   ...                  ...
26950  Vietnam  2020           Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020           Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020           Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020           Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020           Là Gì?     5       Đông Lào là gì

[26945 rows x 5 columns]

In [13]:
df['location'].value_counts(dropna=False)

location
United States         2070
Global                1135
Japan                  765
Canada                 690
Brazil                 675
                      ...
Honduras                 5
El Salvador              5
Dominican Republic       5
Kuwait                   5
Sudan                    5
Name: count, Length: 83, dtype: int64